import { describe, expect, it } from "vitest";

import type { ProbeReport } from "@bsns/probe-core";

import { renderMarkdownReport } from "./markdown.js";

describe("renderMarkdownReport", () => {
  it("renders score, fixes, and footer", () => {
    const markdown = renderMarkdownReport(makeReport());

    expect(markdown).toContain("# bsns probe report for example.com");
    expect(markdown).toContain("Score: A / 100");
    expect(markdown).toContain("## No Urgent Fixes");
    expect(markdown).toContain("No urgent fixes found in the checks that completed.");
    expect(markdown).toContain("Generated by bsns probe");
  });
});

function makeReport(): ProbeReport {
  return {
    schemaVersion: "1.0",
    target: {
      input: "example.com",
      hostname: "example.com",
      asciiHostname: "example.com",
      registrableDomain: "example.com",
      scannedAt: "2026-01-01T00:00:00.000Z"
    },
    score: {
      total: 100,
      grade: "A",
      categories: {
        dns: { score: 20, max: 20 },
        web: { score: 30, max: 30 },
        email: { score: 30, max: 30 },
        headers: { score: 15, max: 15 },
        performance: { score: 5, max: 5 }
      }
    },
    summary: {
      headline: "Scan complete with no urgent fixes found.",
      topFixes: ["No urgent fixes found in the checks that completed."],
      counts: {
        pass: 1,
        warn: 0,
        fail: 0,
        info: 0,
        skip: 0
      }
    },
    findings: [
      {
        id: "perf.response.fast",
        category: "performance",
        status: "pass",
        severity: "info",
        title: "Initial response is fast",
        summary: "The final HTTPS response took about 120 ms."
      }
    ],
    raw: {}
  };
}
