import type { Finding, ProbeReport } from "@bsns/probe-core";

const CATEGORY_LABELS: Record<string, string> = {
  dns: "DNS",
  web: "Web",
  tls: "TLS",
  email: "Email",
  headers: "Headers",
  performance: "Performance",
  meta: "Meta"
};

export function renderMarkdownReport(report: ProbeReport): string {
  const hasPriorityFixes = report.summary.topFixes.some(isPriorityFix);
  const lines = [
    `# bsns probe report for ${report.target.hostname}`,
    "",
    `Scanned: ${report.target.scannedAt}`,
    "",
    `Score: ${report.score.grade} / ${report.score.total}`,
    "",
    "## Summary",
    "",
    report.summary.headline,
    "",
    hasPriorityFixes ? "## Fix These First" : "## No Urgent Fixes",
    ""
  ];

  if (report.summary.topFixes.length === 0) {
    lines.push("No priority fixes found.");
  } else if (!hasPriorityFixes) {
    lines.push(...report.summary.topFixes);
  } else {
    report.summary.topFixes.forEach((fix, index) => {
      lines.push(`${index + 1}. ${fix}`);
    });
  }

  lines.push("", "## Category Scores", "");

  for (const [category, score] of Object.entries(report.score.categories)) {
    lines.push(`- ${CATEGORY_LABELS[category] ?? category}: ${score.score}/${score.max}`);
  }

  lines.push("", "## Findings", "");

  for (const finding of report.findings) {
    lines.push(...renderFinding(finding), "");
  }

  lines.push(
    "---",
    "",
    "Generated by bsns probe — open-source tools for operators."
  );

  return `${lines.join("\n")}\n`;
}

export function renderJsonReport(report: ProbeReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}

function renderFinding(finding: Finding): string[] {
  const lines = [
    `### ${finding.title}`,
    "",
    `- ID: \`${finding.id}\``,
    `- Category: ${CATEGORY_LABELS[finding.category] ?? finding.category}`,
    `- Status: ${finding.status}`,
    `- Severity: ${finding.severity}`,
    `- Summary: ${finding.summary}`
  ];

  if (finding.whyItMatters) {
    lines.push(`- Why it matters: ${finding.whyItMatters}`);
  }

  if (finding.fix) {
    lines.push(`- Fix: ${finding.fix}`);
  }

  return lines;
}

function isPriorityFix(fix: string): boolean {
  return !fix.toLowerCase().startsWith("no urgent fixes");
}
